const Discord = module.require("discord.js");

module.exports = {
  name: "joke",
  description: "Sends a random joke",
  run: async (client, message, args) => {
    var jokes = [
      "Sebenarnya pelajaran matematika di Amerika lebih susah, karena dicampur dengan bahasa Inggris.",
      'Secapek-capeknya kerja, lebih capek nganggur.',
      'Ketika kamu merasa cobaan hidupmu terlalu berat, itu karena Tuhan tau kamu bisa mengatasinya. Kalo masih berat juga, diet dong ah.',
      'Gak papa deh bila kita beda kartu operator,asal nantinya nama kita ada di KARTU Keluarga yang sama.',
      'Jodoh itu kayak penjual gorengan. Ditungguin gak ada yang lewat, pas lagi gak pengen banyak yang lewat. eh pas mau disamperin udah banyak yang ngantri', // thanks to 30 Rock
      'Di mobil kamu ada yang wangi, kalau di mata kamu ada pelangi',
      "Penyesalan pasti datang di akhir, kalo di awal namanya pendaftaran.",
      'Manusia itu emang susah nyalahin diri sendiri. Leher pegel dibilang salah bantal.',
      "Aku mendadak Budek waktu kamu bilang *AKU SAYANG KAMU* Bukan kaga kedengeran tapi cuma pengen kamu ulangI terus.",
      'Mau mandi males, harus jalan ke kamar mandi, ada toilet online nggak yah biar di anterin',
      'Dompetku sama seperti bawang: membukanya membuatku menangis.',
      'Sekali terjatuh, bangunlah, dua kali, tetaplah tegar, jika jatuh lagi juga, makanya kalau jalan pakai mata..',
      "Meskipun sering dipetik, hikmah bukan termasuk dalam kategori alat musik.",
      "Kalo naik motor sama kamu pasti ditilang deh. Soalnya kita kan berTiga, Aku, Kamu, dan Cinta..",
      "Aku itu gak tau kamu itu siapa, terbuat dari apa. yang aku tahu itu cuma satu. kamu udah buat aku jatuh cinta.",
      "Cinta aku ke kamu dijamin tanpa pemanis buatan, pengawet buatan. semua alami murni dari hati..",
      "Kamu tahu, apa persamaan rasa sayangku ke kamu dengan matahari? Persamaannya adalah sama-sama terbit setiap hari dan hanya akan berakhir sampai kiamat.",
      'Kalau disuruh melupakanmu, aku harus ke kantor kelurahan dulu bikin surat keterangan tidak mampu.',
      "Apakah namamu WiFi? Soalnya aku bisa merasakan konektivitas.",
      "Madu di tangan kananmu, racun ditangan kirimu. Tapi, ingat jodoh tetap di tangan Tuhan.",
      "Makanan semahal apa pun nggak akan terasa mahal kalau kamu nggak membelinya.",
      "Dalam hidup pasti akan banyak rintangan. Karena kalau rantangan berarti itu katering.",
      "Kalau kamu sayang sama aku bilang dong. Aku bukan brankas yang butuh kode",
      "Selamat pagi semua! Jangan lupa bernafas, karena percuma tersenyum kalau nggak nafas",
      "Ketika hidup menutup pintu untukmu, maka buka lagi saja. Itu hanya pintu, dan begitulah cara kerjanya",
      'Motivator tak bisa membuatku rajin bekerja. Karena cuma cicilan dan tagihan yang mampu',
      'Seorang laki-laki sukses adalah yang bisa menghasilkan uang lebih dari yang dihabiskan istrinya. Seorang wanita sukses adalah yang bisa mencari laki laki seperti itu',
      "Jika masa depan tergantung pada mimpimu, maka perbanyaklah tidur",
      "Setinggi-tingginya burung bangau terbang, akhirnya jadi kecap juga.",
      "Orang bilang, ngopi sambil ngerokok itu nikmat. Tapi ternyata bohong, buktinya ini susah.",
      'Bercandanya bikin sayang, tapi sayangnya cuma bercanda',
      "Jika kamu sudah bikin kopi tapi ternyata masih tetap mengantuk, berarti kopinya belum kamu minum.",
      "Percayalah, kegagalan bukan suatu keberhasilan.",
      "Cowoknya cool, ceweknya hot, anaknya pasti dispenser.",
      "Sebenarnya pelajaran Matematika di Amerika terasa lebih susah karena dicampur bahasa Inggris.",
      "Bermimpilah sesuka hati tentang apa yang kamu inginkan, sebab itu hanya mimpi",
      "Kuliah lo ambil apa? Gue sih ambil hikmahnya aja.",
      'Tertawa bisa jadi obat terbaik. Tapi kalau kamu tertawa tanpa alasan yang jelas, mungkin kamu butuh obat!"',
      "Aku ingin jadi seperti ulat. Makan yang banyak, tidur cukup, dan terbangun dengan wujud yang indah",
      "Teman sejati tidak tersinggung saat kamu menghinanya. Mereka tersenyum dan balas menghinamu lebih parah lagi..",
      "Teman yang baik akan membantumu pindahan. Tapi teman terbaik akan membantumu memindahkan jasad!",
      "Taukah kamu apa yang lebih lucu dari 23? 24.",
      "Jomblo Bukan Berarti Homo.",
      "Jomblo itu ibarat emas, bila kelamaan tambah mahal hargannya.",
      "Satu bulan tak bertemu kamu, bagaikan 30 hari tanpa kamu.",
      "Cinta itu kaya martabak, manis, enak, gurih. Tapi kalo kebanyakan eneg.",
      "Wanita itu suka es cream dan coklat, namun lebih suka kepastian.",
    ];
    await message.channel.send(jokes[Math.floor(Math.random() * jokes.length)]);
  },
};
